---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: config2
  annotations:
    reloader.stakater.com/auto: "true"
  name: basic-configmap
data:
  application.properties: |-
    bean.message=Hello from OpenShift, Again!
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: config2
  name: basic-configmap
  labels:    
    app: "basic-configmap"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "basic-configmap"
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: basic-configmap
        items:
        - key: application.properties
          path: application.properties
      containers:
      - name: "basic-configmap"
        image: "fabiogomezdiaz/basic-configmap:latest"
        imagePullPolicy: "Always"
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "/etc/config/application.properties"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3